spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    db1:  # 数据源1配置    ~  二开数据库
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
      url: jdbc:mysql://192.168.178.128:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&autoReconnect=true
    db2: # 数据源2配置    ~ 业务数据库库名
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
      url: jdbc:mysql://192.168.178.128:3306/adssp?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    db3: # 数据源2配置    ~ 业务数据库库名
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
      url: jdbc:mysql://192.168.178.128:3306/dpss?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&autoReconnect=true


    mvc:
      format:
        date: yyyy-MM-dd HH:mm
      jpa:
        hibernate:
          ddl-auto: update
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: default
      #驼峰下划线转换
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
